config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  #
  resources :sessions, except: :new
  resources :messages
  root 'chatroom#index'
  get 'login', to: 'sessions#new'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates_uniqueness_of :username, message: 'username already exist'
  validates :username, presence: true, length: { minimum: 3, maximum: 30 }
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:danger] = 'you have to login to use this feature'
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  def index
    @message = Message.new
    @messages = Message.all
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  skip_before_action :verify_authenticity_token


  def create
    # add  message for current user
    message = current_user.messages.build(message_params)
    if message.save
      # de gui du lieu qua socket
      ActionCable.server.broadcast 'chatroom_channel',
                                   mod_message: message_render([message])
    end
  end

  def message_params
    params.require(:message).permit(:body)
  end

  private

  def message_render(message)
    # render(partial: 'message', message: message)
    render_to_string(partial: 'message', locals: { messages: message })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if logged_in?
      redirect_to root_path
    end
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user&.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "login success"
      redirect_to root_path
    else
      flash[:danger] = "login failed"
      render 'new'
    end
  end

  def destroy
    flash[:success] = "logout success"
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned medium icon header">
  <i class="  circular blue comment icon"></i>
  Say something
</h2>



<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox ">
      <div class="content" id="messages">
        <div class="ui medium feed" id="message-container">
          <%= render 'messages/message', messages: @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: { class: "ui reply form", role: "form" }, url: messages_path, remote: true) do |f| %>

          <div class="field">
            <div class="ui fluid icon input ">
              <%= f.text_field :body %>
              <%= f.button '<i class="bordered inverted blue  left icon edit"></i>'.html_safe, id: "send-m", placeholder: "Type message..." %>
            </div>

          </div>

        <% end %>

      </div>
    </div>
  </div>

  <div class="four wide column ">
    <div class="ui card chatbox">
      <div class="content">
        <div class="ui inverted vertical pointing menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="ui large inverted menu">
  <div class="ui container">
    <%= link_to "Chatroom", root_path, class: "item" %>
    <%= link_to "Message", root_path, class: "item" %>

    <div class="right menu">
      <% if logged_in? %>
        <div class="item">
          <!--          <div class="ui primary button">Sign out</div>-->
          <%= button_to "Sign out", session_path(session), method: :delete, class: "ui primary button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChatMessage</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/navigation' %>
<div class="ui container">
  <%= yield %>
</div>

</body>
</html>

app/views/messages/_message.html.erb
<% messages.each do |m| %>
  <div class="event">
    <div class="content">
      <div class="summary">
        <em><a><%= m.user.username %></a></em>: <%= m.body %>
      </div>
    </div>
  </div>
<% end %>